
.define ROM_NAME "PONG"
.define REGION PAL
.define VERSION 1

OBJ_TILES = 0
DIGIT_OFFSET = 3
DIGIT_SPACING = 5

SCORE_YPOS = 20
SCORE_P1_XPOS = 30
SCORE_P2_XPOS = 256 - SCORE_P1_XPOS - DIGIT_SPACING * 2 + 2

BALL_SPRITE = 1
PADDLE_SPRITE = 2

SCREEN_WIDTH  = 256
SCREEN_TOP    = 10
SCREEN_BOTTOM = 224 - SCREEN_TOP

MAX_XVECL = BALL_WIDTH << 8
START_BALL_XVECL = $0190
START_BALL_YVECL = $0000

PADDLE_ACCEL = $0180
PADDLE_FRICTION = $00C0
PADDLE_MAX_VECL = $0600
PADDLE_HEIGHT = 24

PADDLE_P1_XPOS = 24
PADDLE_P2_XPOS = 256 - PADDLE_P1_XPOS - 1
PADDLE_WIDTH = 2

BALL_WIDTH = 3
BALL_HEIGHT = 3

; vim: ft=asm:


